#workflow name
name: Upload Apk Build

on:
# When it will be triggered
# And in what branch
  push:
    branches:
      - main
# Where they will run
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      ##Checkout our repository ###
      - name: Checkout
        uses: actions/checkout@2.4.0

      - name: Setup our enviornment
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      ##Build all of our build types at once ##
      - name: Build all artifacts
        id: buildAllApks
        uses: eskatos/gradle-command-action@v1.3.3
        with:
          gradle-version: current
          wrapper-cache-enabled: true
          dependencies-cache-enabled: true
          configuration-cache-enabled: true
          arguments: assembleRelease


      ##Sign our artifact##
      - name: Sign Artifact
        id: signArtifact
        uses: r0adkll/sign-android-release@v1.0.1
        with:
         releaseDirectory: app/build/outputs/apk/ourbuildtype/release
         alias: ${{secrets.KEYALIAS}}
         signingKeyBase64: ${{ secrets.KEYSTORE }}
         keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
         keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload our APK
        uses: actions/upload-artifact@v2.2.0
        with:
          name: Release artifact
          path: app/build/outputs/apk/ourbuildtype/release/app-artifact-*.apk

